from enum import StrEnum


class TaskStatusEnum(StrEnum):
    BACKLOG = "BACKLOG"
    TODO = "TODO"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    CANCELED = "CANCELED"


class TaskTypeEnum(StrEnum):
    NEW_FEATURE = "NEW_FEATURE"
    FEATURE_MODIFICATION = "FEATURE_MODIFICATION"
    AUTOMATION_BATCH = "AUTOMATION_BATCH"
    POLICY_CHANGE = "POLICY_CHANGE"
